#!/bin/bash

# If you are running this script from a different directory (e.g., ~/bin) set DATA_DIR path to 'Reference' directory 
# containing .md files

DATA_DIR=.

if [ "$#" -eq 1 ]; then
  if [[ "$OSTYPE" == "darwin"* ]]; then
    OPEN=open
  elif [[ "$OSTYPE" == "linux"* ]] && [[ $DISPLAY ]]; then
    OPEN=xdg-open
  else
    OPEN=less
  fi

  $OPEN $DATA_DIR/$1.md
else
  script_name=`basename "$0"`
  topics=`cd $DATA_DIR; ls *.md | sed 's/\.md//' | sed 's/Readme//'`

  echo "Usage: $script_name <topic>"
  echo ""
  echo "Where topic is one of:"
  echo ""
  echo "$topics"
  exit 1
fi

